CREATE TABLE IF NOT EXISTS users (
    UserID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Email VARCHAR(64) NOT NULL UNIQUE,
    Password VARCHAR(256),
    Username VARCHAR(256) NOT NULL UNIQUE,
    Region CHAR(2),
    Avatar TEXT,
    Fecha_Registro TIMESTAMP DEFAULT now(),
    Notifications BOOLEAN DEFAULT false,
    Perfil_Publico BOOLEAN DEFAULT true,
    GoogleID VARCHAR(30) UNIQUE,

    CHECK (Password IS NOT NULL OR GoogleID IS NOT NULL)
);
CREATE TABLE IF NOT EXISTS books (
    BookID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title VARCHAR(512),
    Sinopsis TEXT,
    Autores TEXT,
    Portada TEXT,
    Paginas INT,
    Idioma VARCHAR(10), 
    Link_Compra TEXT,
    Link_Gratis TEXT,
    Fecha_Publicacion VARCHAR(10), 
    Google_Books_ID VARCHAR(30) NOT NULL UNIQUE,
    Fecha_Cacheada TIMESTAMP DEFAULT now(),
    Cantidad_Interacciones INT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS categorias (
    CategoryID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Category_Name VARCHAR(64) NOT NULL
);
CREATE TABLE IF NOT EXISTS book_in_category (
    BookID INT,
    CategoryID INT,

    PRIMARY KEY(BookID, CategoryID),

    FOREIGN KEY (BookID) REFERENCES books(BookID) ON DELETE CASCADE,
    FOREIGN KEY (CategoryID) REFERENCES categorias(CategoryID)
);
CREATE TABLE IF NOT EXISTS preference_category (
    UserID INT,
    CategoryID INT,
    Preference_Weight INT,

    PRIMARY KEY(UserID, CategoryID),

     FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE,
     FOREIGN KEY (CategoryID) REFERENCES categorias(CategoryID)
);
CREATE TABLE IF NOT EXISTS preferences (
    PreferenceID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID INT NOT NULL,
    BookID INT NOT NULL,

     UNIQUE(BookID, UserID),
     FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE,
     FOREIGN KEY (BookID) REFERENCES books(BookID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS books_progress (
    ProgressID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID INT NOT NULL,
    BookID INT NOT NULL,
    Book_State VARCHAR(13), -- 13 porque el más grande es "abandonado". Lo voy a cambiar dsp si cambiamos como funciona esto.
    /* Se puede cambiar a ENUM si confirmamos que vamos a usar un POSGRESQL */
    Puntuacion INT CHECK (Puntuacion BETWEEN 1 AND 5),
    Amount_Read INT,
    Starting_Date DATE,

     UNIQUE(BookID, UserID),
     FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE,
     FOREIGN KEY (BookID) REFERENCES books(BookID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS reviews (
    BookID INT NOT NULL,
    UserID INT NOT NULL,
    ReviewID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Review_Content TEXT,
    Creation_Date TIMESTAMP DEFAULT now(),

    UNIQUE(BookID, UserID),
     FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE,
     FOREIGN KEY (BookID) REFERENCES books(BookID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS followers (
    FollowingID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FollowerID INT NOT NULL,
    FollowedID INT NOT NULL,
    Following_Date TIMESTAMP DEFAULT now(),

    UNIQUE(FollowerID, FollowedID),
    CHECK (FollowerID <> FollowedID), 
    FOREIGN KEY (FollowerID) REFERENCES users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (FollowedID) REFERENCES users(UserID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS lists (
    listsID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID INT NOT NULL,
    lists_Name VARCHAR(64) NOT NULL,
    Is_Public BOOLEAN DEFAULT true,
    Date_Created TIMESTAMP DEFAULT now(),

    UNIQUE(UserID, lists_Name),
     FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS books_in_lists (
    Book_In_listsID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BookID INT NOT NULL,
    listsID INT NOT NULL,
    Book_Order SMALLINT,

    UNIQUE(BookID, listsID),
    FOREIGN KEY (BookID) REFERENCES books(BookID) ON DELETE CASCADE,
    FOREIGN KEY (listsID) REFERENCES lists(listsID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS likes (
    UserID INT,
    listsID INT,

    PRIMARY KEY(UserID, listsID),
     FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE,
     FOREIGN KEY (listsID) REFERENCES lists(listsID) ON DELETE CASCADE
);
