/*

ESTE ARCHIVO ES PARA INCLUIR TODAS LAS COSAS "UTILES" QUE TENEMOS QUE EXPORTAR / IMPORTAR MAS DE UNA VEZ
O PARA COSAS QUE QUEREMOS PODER CAMBIAR MUY FACILMENTE. 
ES COMO PONER UN #define EN ARDUINO

*/